import React from 'react'

export const Images = [
    {id:'0', src: 'asset/img/banner-digital-graphics-bird.jpg'},
    {id:'1', src: 'asset/img/istockphoto-1364958983-612x612.jpg'},
    {id:'2', src: 'asset/img/group-little-birds-perching-on-260nw-2056880072.jpg'},
]

export const Food =[
    {title:'Pennington Classic Wild Bird Feed and Seed, 20 lb. Bag', img: 'asset/img/pennington-bird-seed-food-100542060-64_1000.jpg',info: 'Pennington® Classic Wild Bird Feed is a blend of high-quality grains and seeds that attract a wide variety of beautiful & colorful wild birds. Pennington® Classic Wild Bird Feed is blended with desirable grains such as white millet and black oil sunflower seed and is great to feed year-round. Pennington® Classic Wild Bird Feed is a good mix to feed in many types of bird feeders including hopper, gazebo and tube feeders. Pennington® ClassicWild Bird Feed attracts songbirds just as Cardinals, Goldfinches and Chickadees. Condition: New'
},// ,star:}
{title:'Kaytee Wild Bird Food Nut & Fruit Blend', img: 'asset/img/81kMojdC7rS.jpg',info: 'Wild birds require a lot of energy for flying. Offer them the Kaytee Nut & Fruit Blend to keep them fueled and happy. Pound for pound, nothing offers your feathered friend more energy than fruit and nuts. Provide a supply of All Living Things Nyjer Seed year-round as birds may abandon and not return to a feeding area if they find it empty. When offering more than one type of seed, place feeders at different heights to avoid conflicts between different types of birds. Always provide plenty of clean, fresh water.'
},
{title:'Mazuri | Nutritionally Complete for Small Birds | 2.5 Pound (2.5 lb.) Bag', img:'asset/img/Small-Bird-2-5lb-727613010935-center-1_37ef0caf-d638-4874-8a76-74985a20bb03.jpg',info: "There is a special group of people who love exotic animals. At Mazuri we are fascinated by the world's less-common creatures. When kept as pets, exotic animals require special care and expertise, so we've spent decades mastering their needs. That's why we're trusted by both pet owners and professionals to provide high-quality nutrition for exotic animals of all kinds. We're committed to creating the most nutritious exotic pet foods possible based on science, research, and more than 30 years of experience"}
,
{title:'Pennington Wild Bird Premium Select Blend Feed and Seed, 20 lb.', img:'asset/img/5bf981ed-12ba-4c32-aeca-a3742e7e5e62.66e5c54de760eeedd8039bac9372a1b3.jpg', info:"Pennington Wild Bird Premium Select Blend Feed and Seed is a special treat for wild birds. Pennington Wild Bird Premium Select Blend Feed and Seed contains a large amount of Sunflower Seed that most every bird loves plus many other high-quality grains to please even the most discriminating birds. Pennington Wild Bird Premium Select Blend Feed and Seed is blended with desirable grains such as white millet and black oil sunflower seed and is great to feed year-round. Pennington Wild Bird Premium Select Blend Feed and Seed is a good mix to feed in many types of bird feeders including hopper, gazebo and tube feeders. Pennington Wild Bird Premium Select Blend Feed and Seed attracts songbirds such as Cardinals, Chickadees and Purple Finches. Condition is New."}
]